codecov:
  notify:
    require_ci_to_pass: true
comment:
  behavior: default
  layout: header, diff
  require_changes: false
coverage:
  precision: 5
  range:
  - 50.0
  - 75.0
  round: down
  status:
    changes: false
    patch: true
    project:
      default:
        target: 40
        threshold: 100
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
